name: 'Create new project'
description: 'Creates new project from a clone of this repository.'

inputs:
  project:
    required: true
    description: Name of the project to create
  token:
    required: true
    description: GitHub token
outputs:
 repository:
   description: 'Created repository in owner/repo format.'
   value: ${{ github.repository_owner	 }}/${{ inputs.project }}

runs:
  using: 'composite'
  steps:
    - name: Download repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
    - name: Create new repository and push contents
      run: gh repo create ${{ inputs.project }} --private --source=. --push --remote=upstream
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash

### Token:
# all repo
# all workflow
# write:org