name: 'Create new project'
description: "This GitHub Action enables you to create new GitHub projects using your current project as a template. It simplifies the process of creating new projects for your development team by providing predefined templates. When triggered, this action creates a new GitHub project by duplicating the current project\'s structure and files."

inputs:
  project:
    required: true
    description: Name of the new project to be created.
  token:
    required: true
    description: 'GitHub token. Should have the following permissions: `all repo`, `all workflow`, `write:org` .''
outputs:
 repository:
   description: 'Created repository in owner/repo format.'
   value: ${{ github.repository_owner	 }}/${{ inputs.project }}

runs:
  using: 'composite'
  steps:
    - name: Download repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
    - name: Create new repository and push contents
      run: gh repo create ${{ inputs.project }} --private --source=. --push --remote=upstream
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
