name: Create new project

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
        type: string
        description: Name of the project to create

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: hekonsek/action-create-new-project
      with:
        project: deleteme-${{ github.event.inputs.project }}
        token: ${{ secrets.GH_TOKEN }}